### ISSUE TITLE
Enhancement: Add auto-revert and copied confirmation to Copy Markdown button

### ISSUE THREAD

**Issue by Udit-H** [rahuldkjain/github-profile-readme-generator#915]
### 🧾 **Issue Title**
Copy Markdown button does not revert to original text after copying the markdown file.

---

### 🐞 **Description**
When using the **Copy Markdown** button after generating a README, the button text changes to **“Copied”** but does not revert back to its original state.  
Additionally, there’s no visual confirmation (other than the button text) indicating that the markdown was successfully copied.

---

### 💡 **Expected Behavior**
- After clicking **Copy Markdown**, the text should:
  1. Display a short success message — e.g., “Copied!” or a small tooltip/toast notification 💬  
  2. Revert the button text back to **“Copy Markdown”** after 2 seconds 🔄  

---

### ⚙️ **Steps to Reproduce**
1. Generate a README using the generator.
2. Click the **Copy Markdown** button.
3. Observe that the button text stays as “Copied” and doesn’t revert.

---

### 🧠 **Proposed Solution**
Implement a small timeout and optional message display:
- Temporarily set the button text to `"Copied!"`.
- Use `setTimeout()` to reset it after ~2 seconds.
- Display a short “Copied to clipboard” message below.

**Comment by rahuldkjain** [comment]
## 🚀 V1 Deprecated - V2 Released!

Hi! We've released a **complete V2 rewrite** with Next.js 15, React 19, and modern TypeScript.

**V1 Status:** ❌ **Deprecated** - No further development
**V2 Status:** ✅ **Active** - All new development

**Your V1 issue:**
- This V1 item is now **deprecated**
- V1 codebase is no longer maintained  
- Many V1 issues are **already fixed** in V2's rewrite

**Next Steps:**
1. 🧪 **Test V2:** https://rahuldkjain.github.io/github-profile-readme-generator
2. 🐛 **Still broken?** Create a **new issue** with our updated templates
3. 💡 **New feature?** Submit as **feature request**

**This issue will be closed in 2 weeks** unless recreated for V2.

**V2 Benefits:**
- 🚀 3x faster performance
- 📱 Mobile-first responsive design
- ♿ Full accessibility compliance
- 🔒 Privacy-first analytics

Join our Discord for V2 support: https://discord.gg/HHMs7Eg

Thank you for helping make GPRG better! 🙏

**Comment by DipakHalkude** [comment]
@rahuldkjain Just wanted to let you know that the Copy Markdown button issue is still present in V2 - the button text stays as "Copied" and doesn't revert back, and there's still some blinking/shrinking animation when clicking it.

**Comment by rahuldkjain** [comment]
This is the V2 link: https://rahuldkjain.github.io/github-profile-readme-generator/

**Comment by DipakHalkude** [comment]
Now it is proper and something new one :)

**Comment by DipakHalkude** [comment]
@rahuldkjain  I think here just give the new V2 version video...

<img width="1010" height="433" alt="Image" src="https://github.com/user-attachments/assets/9123c994-34a4-4624-a346-cc7902a6c86f" />

**Comment by rahuldkjain** [comment]
please create a new ticket, will assign it to you.

**Comment by DipakHalkude** [comment]
@rahuldkjain Just created it [https://github.com/rahuldkjain/github-profile-readme-generator/issues/932](url) Please assign to me :)
